# 什么是PyTorch？

这是一个基于Python的科学计算包，主要分入如下2部分：

- 使用GPU的功能代替numpy
- 一个深刻的学习研究平台，提供最大的灵活性和速度

## 开始学习
### Tensors (张量)
Tensors类似于`numpy`的`ndarrays`，另外还可以在GPU上使用`Tensors`来加速计算。

In [1]:
from __future__ import print_function
import torch

构造一个5x3矩阵，不初始化。

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.6932e+22, 7.7144e+31, 6.7109e+22],
        [1.6486e+22, 4.3605e+27, 2.8929e+12],
        [7.5338e+28, 1.8037e+28, 3.4740e-12],
        [1.7743e+28, 6.8239e+16, 1.8832e+34],
        [1.6078e+19, 4.4721e+21, 5.0789e-11]])


构造一个随机初始化的矩阵：

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2712, 0.3545, 0.5300],
        [0.0976, 0.0149, 0.8799],
        [0.7187, 0.7343, 0.4521],
        [0.4418, 0.0132, 0.2708],
        [0.9201, 0.0794, 0.4476]])


构造一个矩阵全为 0，而且数据类型是 long.

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


构造一个张量，直接使用数据：

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


创建一个 tensor 基于已经存在的 tensor。

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)     
print(x)

x = torch.randn_like(x, dtype=torch.float)    
print(x)                                     

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.2157, -0.6880,  0.3270],
        [-0.3162, -0.2479,  0.8731],
        [-0.3330, -0.3823,  0.5237],
        [-1.3132, -0.1246,  0.6706],
        [ 1.1174, -1.0695,  0.7972]])


获取它的维度信息:

In [7]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>注意</h4><p>``torch.Size`` 是一个元组，所以它支持左右的元组操作。</p></div>

## 操作
在接下来的例子中，我们将会看到加法操作。 

加法: 方式 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.4000,  0.0549,  1.2980],
        [ 0.0748,  0.5602,  1.2120],
        [ 0.1771, -0.1623,  1.4076],
        [-0.4690,  0.6656,  0.8570],
        [ 1.5434, -0.8243,  1.4676]])


加法: 方式2

In [9]:
print(torch.add(x, y))

tensor([[-0.4000,  0.0549,  1.2980],
        [ 0.0748,  0.5602,  1.2120],
        [ 0.1771, -0.1623,  1.4076],
        [-0.4690,  0.6656,  0.8570],
        [ 1.5434, -0.8243,  1.4676]])


加法: 提供一个输出 tensor 作为参数

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.4000,  0.0549,  1.2980],
        [ 0.0748,  0.5602,  1.2120],
        [ 0.1771, -0.1623,  1.4076],
        [-0.4690,  0.6656,  0.8570],
        [ 1.5434, -0.8243,  1.4676]])


加法: in-place

In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.4000,  0.0549,  1.2980],
        [ 0.0748,  0.5602,  1.2120],
        [ 0.1771, -0.1623,  1.4076],
        [-0.4690,  0.6656,  0.8570],
        [ 1.5434, -0.8243,  1.4676]])


<div class="alert alert-info"><h4>注意</h4><p>任何使张量会发生变化的操作都有一个前缀 '_'。例如： ``x.copy_(y)``, ``x.t_()``, 将会改变  ``x``.</p></div>

你可以使用标准的  NumPy 类似的索引操作

In [12]:
print(x[:, 1])

tensor([-0.6880, -0.2479, -0.3823, -0.1246, -1.0695])


改变大小：如果你想改变一个 tensor 的大小或者形状，你可以使用 `torch.view`

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有一个元素 `tensor` ，可以使用 `.item()` 来获得这个 `tensor` 的值 。

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4592])
-0.4592222571372986


## Numpy转换
将Tensor转换为numpy数组

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


看看numpy数组的值如何变化。

In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


将 `numpy` 数组转换为`Torch`张量

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


除了 `CharTensor` ,CPU 上的所有 `Tensors` 与 `NumPy` 都可以相互转化

## CUDA Tensors

可以通过 `.to` 方法将 `Tensors` 转移到任何设备

In [19]:
# 在GPU可用时运行
# 我们将使用 torch.device 对象将 tensors 移入、移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # 创建一共 CUDA设备对象
    y = torch.ones_like(x, device=device)  # 在GPU上直接创建一个 tensor
    x = x.to(device)                       # 等价于：x = x.to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # .to() 将同时改变数据类型

tensor([0.5408], device='cuda:0')
tensor([0.5408], dtype=torch.float64)
